user:
  username: zhangsan
  password: 123456
  map: {name: zhangsan,password: 123456}
  list: [zhangsan,lisi]

server:
  port: 8081
spring:
  profiles:
    active: dev
---
server:
  port: 8082
spring:
  profiles: dev